### PR TITLE
Build on Linux

### PR DESCRIPTION
**Pull request by uilianries**
- Tested on Linux and Windows
- Plugins is kind of broken, requires mosquitto for both platforms, but cmake says only for Windows. It could be disabled for now.

### CODE REVIEW

**Comment by a4z** [comment]
So sorry @uilianries , I do not get mail notifications when a PR on this repos happens, so I have seen the changes you submitted just now. 
I will look into them asap, maybe already later this evening

**Comment by a4z** [comment]
I have serious problems on Windows when I merge that, linking with openssl,  and I do not understand why.
Also when I change back the patch_source to the previous version.
maybe you see something obvious ? What I work with after the merge is here:
https://github.com/a4z/conan-center-index/pull/new/uilianries-mosquitto-2.0.3

**Comment by uilianries** [comment]
Let me try on Windows. I only tested on Linux.

**Comment by uilianries** [comment]
@a4z It's on Windows now. Please, update.

**Comment by a4z** [comment]
I have now simply take over your work, @uilianries  :-) 

did not merge, just copied your files, that was faster

**Pull request merged**
